"""add markets tables

Revision ID: 82e84f59efc9
Revises: d8e2b6c41f90
Create Date: 2026-10-01 22:29:50.528463
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "82e84f59efc9"
down_revision: str | Sequence[str] | None = "d8e2b6c41f90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("venue_group", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("call_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("selection", sa.String(length=256), nullable=False),
        sa.Column("entry", sa.Float(), nullable=True),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("stop", sa.Float(), nullable=True),
        sa.Column("horizon_hours", sa.Float(), nullable=True),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("market_price", sa.Float(), nullable=True),
        sa.Column("fair_price", sa.Float(), nullable=True),
        sa.Column("model_probability", sa.Float(), nullable=True),
        sa.Column("lower_90", sa.Float(), nullable=True),
        sa.Column("edge", sa.Float(), nullable=True),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("edge_class", sa.String(length=20), nullable=False),
        sa.Column("stake_pct", sa.Float(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("price_gap", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("market_calls", schema=None) as batch_op:
        batch_op.create_index("ix_market_calls_board", ["venue_group", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_market_calls_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_market_calls_instrument_id"), ["instrument_id"], unique=False
        )
        batch_op.create_index("ix_market_calls_model", ["model_version"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_calls_venue"), ["venue"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_market_calls_venue_group"), ["venue_group"], unique=False
        )
        batch_op.create_index("ix_market_calls_verdict", ["verdict"], unique=False)

    op.create_table(
        "market_candles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("granularity", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue", "instrument_id", "granularity", "ts", name="uq_market_candle"),
    )
    with op.batch_alter_table("market_candles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_market_candles_lookup",
            ["venue", "instrument_id", "granularity", "ts"],
            unique=False,
        )

    op.create_table(
        "market_instruments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=True),
        sa.Column("league", sa.String(length=64), nullable=True),
        sa.Column("contract_rules", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue", "instrument_id", name="uq_market_instrument"),
    )
    with op.batch_alter_table("market_instruments", schema=None) as batch_op:
        batch_op.create_index("ix_market_instruments_kind", ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_instruments_venue"), ["venue"], unique=False)

    op.create_table(
        "market_job_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_name", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_job_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_market_job_runs_name_started", ["job_name", "started_at"], unique=False
        )

    op.create_table(
        "market_model_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    with op.batch_alter_table("market_model_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_model_versions_kind"), ["kind"], unique=False)

    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.Column("last", sa.Float(), nullable=True),
        sa.Column("spread", sa.Float(), nullable=True),
        sa.Column("depth_summary", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_market_snapshots_instrument_time",
            ["venue", "instrument_id", "fetched_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_market_snapshots_venue"), ["venue"], unique=False)

    op.create_table(
        "market_outcomes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("call_id", sa.String(length=36), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("realized_return", sa.Float(), nullable=True),
        sa.Column("closing_price", sa.Float(), nullable=True),
        sa.Column("brier", sa.Float(), nullable=True),
        sa.Column("grading_method", sa.String(length=32), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["call_id"], ["market_calls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_outcomes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_outcomes_call_id"), ["call_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_market_outcomes_outcome"), ["outcome"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_outcomes_outcome"))
        batch_op.drop_index(batch_op.f("ix_market_outcomes_call_id"))

    op.drop_table("market_outcomes")
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_snapshots_venue"))
        batch_op.drop_index("ix_market_snapshots_instrument_time")

    op.drop_table("market_snapshots")
    with op.batch_alter_table("market_model_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_model_versions_kind"))

    op.drop_table("market_model_versions")
    with op.batch_alter_table("market_job_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_market_job_runs_name_started")

    op.drop_table("market_job_runs")
    with op.batch_alter_table("market_instruments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_instruments_venue"))
        batch_op.drop_index("ix_market_instruments_kind")

    op.drop_table("market_instruments")
    with op.batch_alter_table("market_candles", schema=None) as batch_op:
        batch_op.drop_index("ix_market_candles_lookup")

    op.drop_table("market_candles")
    with op.batch_alter_table("market_calls", schema=None) as batch_op:
        batch_op.drop_index("ix_market_calls_verdict")
        batch_op.drop_index(batch_op.f("ix_market_calls_venue_group"))
        batch_op.drop_index(batch_op.f("ix_market_calls_venue"))
        batch_op.drop_index("ix_market_calls_model")
        batch_op.drop_index(batch_op.f("ix_market_calls_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_market_calls_created_at"))
        batch_op.drop_index("ix_market_calls_board")

    op.drop_table("market_calls")
    # ### end Alembic commands ###
