"""initial ywp os v3 schema

Revision ID: 865f21ad51d1
Revises:
Create Date: 2026-09-03 08:44:33.408175
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "865f21ad51d1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=100), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=False),
        sa.Column("slate_date", sa.Date(), nullable=False),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_game_snapshots_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_game_snapshots_event_id"), ["event_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_game_snapshots_input_hash"), ["input_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_game_snapshots_slate_date"), ["slate_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_game_snapshots_sport"), ["sport"], unique=False)

    op.create_table(
        "model_weights",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=False),
        sa.Column("market_type", sa.String(length=50), nullable=False),
        sa.Column("feature_name", sa.String(length=80), nullable=False),
        sa.Column("weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("source_proposal_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sport", "market_type", "feature_name", "version", name="uq_model_weight_version"
        ),
    )
    with op.batch_alter_table("model_weights", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_weights_feature_name"), ["feature_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_model_weights_is_active"), ["is_active"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_model_weights_market_type"), ["market_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_model_weights_sport"), ["sport"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("risk_profile", sa.String(length=24), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "bankroll_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_stake_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("max_daily_exposure_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("max_thesis_exposure_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("loss_pause_threshold", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bankroll_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bankroll_accounts_user_id"), ["user_id"], unique=True)

    op.create_table(
        "protocol_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=False),
        sa.Column("run_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("superseded_rules_ignored", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("protocol_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_protocol_runs_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_protocol_runs_protocol_version"), ["protocol_version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_protocol_runs_run_type"), ["run_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_protocol_runs_sport"), ["sport"], unique=False)
        batch_op.create_index(batch_op.f("ix_protocol_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_protocol_runs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("candidate_id", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.String(length=100), nullable=False),
        sa.Column("event_name", sa.String(length=180), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=False),
        sa.Column("league", sa.String(length=40), nullable=False),
        sa.Column("slate_date", sa.Date(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("market_type", sa.String(length=50), nullable=False),
        sa.Column("market_period", sa.String(length=32), nullable=False),
        sa.Column("selection", sa.String(length=180), nullable=False),
        sa.Column("line", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("american_odds", sa.Integer(), nullable=False),
        sa.Column("estimated_probability", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("implied_probability", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("adjusted_probability", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("edge", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("expected_value", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("confidence_score", sa.Integer(), nullable=False),
        sa.Column("ywp_rating", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("vision_score", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("miss_by_one_risk", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("reliability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("stability", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("variance", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("data_quality", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("risk", sa.String(length=20), nullable=False),
        sa.Column("risk_tier", sa.String(length=20), nullable=False),
        sa.Column("variance_rating", sa.String(length=20), nullable=False),
        sa.Column("edge_class", sa.String(length=20), nullable=False),
        sa.Column("expected_value_label", sa.String(length=16), nullable=False),
        sa.Column("suggested_stake_pct", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("recommendation_tier", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("reasoning_summary", sa.Text(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("safer_alternative", sa.String(length=180), nullable=True),
        sa.Column("higher_upside", sa.String(length=180), nullable=True),
        sa.Column("invalidation_conditions", sa.JSON(), nullable=False),
        sa.Column("live_trigger", sa.String(length=255), nullable=True),
        sa.Column("hedge", sa.String(length=255), nullable=True),
        sa.Column("quick_cash", sa.Boolean(), nullable=False),
        sa.Column("chain_reaction_key", sa.String(length=160), nullable=True),
        sa.Column("thesis_key", sa.String(length=160), nullable=False),
        sa.Column("script_key", sa.String(length=160), nullable=False),
        sa.Column("player_key", sa.String(length=120), nullable=True),
        sa.Column("data_source", sa.String(length=64), nullable=False),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index("ix_recommendations_analysis", ["analysis_id", "rank"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recommendations_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_chain_reaction_key"),
            ["chain_reaction_key"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_created_by_user_id"),
            ["created_by_user_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_recommendations_decision"), ["decision"], unique=False)
        batch_op.create_index(batch_op.f("ix_recommendations_event_id"), ["event_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recommendations_input_hash"), ["input_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_market_type"), ["market_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recommendations_outcome"), ["outcome"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recommendations_player_key"), ["player_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_protocol_version"), ["protocol_version"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_quick_cash"), ["quick_cash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_recommendation_tier"),
            ["recommendation_tier"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_script_key"), ["script_key"], unique=False
        )
        batch_op.create_index(
            "ix_recommendations_slate", ["sport", "slate_date", "decision"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_slate_date"), ["slate_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recommendations_sport"), ["sport"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recommendations_thesis_key"), ["thesis_key"], unique=False
        )

    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_sessions_jti"), ["jti"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_refresh_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_refresh_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=False),
        sa.Column("slate_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stake", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("potential_payout", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("combined_decimal_odds", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("risk", sa.String(length=20), nullable=False),
        sa.Column("confidence_score", sa.Integer(), nullable=False),
        sa.Column("intentional_correlation", sa.Boolean(), nullable=False),
        sa.Column("intentional_thesis_exposure", sa.Boolean(), nullable=False),
        sa.Column("override_acknowledged", sa.Boolean(), nullable=False),
        sa.Column("last_lock_status", sa.String(length=24), nullable=True),
        sa.Column("last_lock_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickets_slate_date"), ["slate_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_tickets_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_tickets_ticket_type"), ["ticket_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_tickets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "weight_change_proposals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=False),
        sa.Column("market_type", sa.String(length=50), nullable=False),
        sa.Column("feature_name", sa.String(length=80), nullable=False),
        sa.Column("current_weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("proposed_weight", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("repeated_pattern_count", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_weight_id", sa.String(length=36), nullable=True),
        sa.Column("rollback_of_proposal_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weight_change_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_weight_change_proposals_feature_name"), ["feature_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_weight_change_proposals_market_type"), ["market_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_weight_change_proposals_sport"), ["sport"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_weight_change_proposals_status"), ["status"], unique=False
        )

    op.create_table(
        "bankroll_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bankroll_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reference_id", sa.String(length=64), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bankroll_id"], ["bankroll_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bankroll_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bankroll_transactions_bankroll_id"), ["bankroll_id"], unique=False
        )

    op.create_table(
        "learning_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recommendation_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("sport", sa.String(length=24), nullable=True),
        sa.Column("market_type", sa.String(length=50), nullable=True),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learning_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_events_market_type"), ["market_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_events_recommendation_id"), ["recommendation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_learning_events_sport"), ["sport"], unique=False)

    op.create_table(
        "lock_checks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("lock_status", sa.String(length=24), nullable=False),
        sa.Column("ticket_confidence_score", sa.Integer(), nullable=False),
        sa.Column("recommended_action", sa.String(length=40), nullable=False),
        sa.Column("overall_message", sa.Text(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("leg_results", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lock_checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lock_checks_input_hash"), ["input_hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lock_checks_lock_status"), ["lock_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lock_checks_ticket_id"), ["ticket_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lock_checks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("final_score", sa.String(length=120), nullable=True),
        sa.Column("stake", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("profit_loss", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("closing_odds", sa.Integer(), nullable=True),
        sa.Column("closing_line", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("clv_probability", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("line_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("actual_value", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("bet_line", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("miss_distance", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("killed_ticket", sa.Boolean(), nullable=False),
        sa.Column("last_losing_leg", sa.Boolean(), nullable=False),
        sa.Column("process_outcome_class", sa.String(length=40), nullable=False),
        sa.Column("error_category", sa.String(length=50), nullable=True),
        sa.Column("assumptions_review", sa.JSON(), nullable=False),
        sa.Column("unexpected_events", sa.JSON(), nullable=False),
        sa.Column("quick_cash_result", sa.String(length=24), nullable=True),
        sa.Column("chain_reaction_result", sa.String(length=24), nullable=True),
        sa.Column("live_trigger_result", sa.String(length=24), nullable=True),
        sa.Column("process_grade", sa.String(length=8), nullable=False),
        sa.Column("variance_grade", sa.String(length=8), nullable=False),
        sa.Column("root_cause_tags", sa.JSON(), nullable=False),
        sa.Column("lesson", sa.Text(), nullable=True),
        sa.Column("result_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_results_error_category"), ["error_category"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_results_outcome"), ["outcome"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_results_recommendation_id"), ["recommendation_id"], unique=True
        )

    op.create_table(
        "ticket_legs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("selection", sa.String(length=180), nullable=False),
        sa.Column("american_odds", sa.Integer(), nullable=False),
        sa.Column("thesis_key", sa.String(length=160), nullable=False),
        sa.Column("script_key", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("skip_reason", sa.String(length=255), nullable=True),
        sa.Column("replacement_for_leg_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_id", "position", name="uq_ticket_leg_position"),
    )
    with op.batch_alter_table("ticket_legs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ticket_legs_recommendation_id"), ["recommendation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ticket_legs_script_key"), ["script_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_ticket_legs_thesis_key"), ["thesis_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_ticket_legs_ticket_id"), ["ticket_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticket_legs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_legs_ticket_id"))
        batch_op.drop_index(batch_op.f("ix_ticket_legs_thesis_key"))
        batch_op.drop_index(batch_op.f("ix_ticket_legs_script_key"))
        batch_op.drop_index(batch_op.f("ix_ticket_legs_recommendation_id"))

    op.drop_table("ticket_legs")
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_results_recommendation_id"))
        batch_op.drop_index(batch_op.f("ix_results_outcome"))
        batch_op.drop_index(batch_op.f("ix_results_error_category"))

    op.drop_table("results")
    with op.batch_alter_table("lock_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lock_checks_user_id"))
        batch_op.drop_index(batch_op.f("ix_lock_checks_ticket_id"))
        batch_op.drop_index(batch_op.f("ix_lock_checks_lock_status"))
        batch_op.drop_index(batch_op.f("ix_lock_checks_input_hash"))

    op.drop_table("lock_checks")
    with op.batch_alter_table("learning_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_events_sport"))
        batch_op.drop_index(batch_op.f("ix_learning_events_recommendation_id"))
        batch_op.drop_index(batch_op.f("ix_learning_events_market_type"))
        batch_op.drop_index(batch_op.f("ix_learning_events_event_type"))

    op.drop_table("learning_events")
    with op.batch_alter_table("bankroll_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bankroll_transactions_bankroll_id"))

    op.drop_table("bankroll_transactions")
    with op.batch_alter_table("weight_change_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weight_change_proposals_status"))
        batch_op.drop_index(batch_op.f("ix_weight_change_proposals_sport"))
        batch_op.drop_index(batch_op.f("ix_weight_change_proposals_market_type"))
        batch_op.drop_index(batch_op.f("ix_weight_change_proposals_feature_name"))

    op.drop_table("weight_change_proposals")
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_user_id"))
        batch_op.drop_index(batch_op.f("ix_tickets_ticket_type"))
        batch_op.drop_index(batch_op.f("ix_tickets_status"))
        batch_op.drop_index(batch_op.f("ix_tickets_slate_date"))

    op.drop_table("tickets")
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_jti"))

    op.drop_table("refresh_sessions")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_thesis_key"))
        batch_op.drop_index(batch_op.f("ix_recommendations_sport"))
        batch_op.drop_index(batch_op.f("ix_recommendations_slate_date"))
        batch_op.drop_index("ix_recommendations_slate")
        batch_op.drop_index(batch_op.f("ix_recommendations_script_key"))
        batch_op.drop_index(batch_op.f("ix_recommendations_recommendation_tier"))
        batch_op.drop_index(batch_op.f("ix_recommendations_quick_cash"))
        batch_op.drop_index(batch_op.f("ix_recommendations_protocol_version"))
        batch_op.drop_index(batch_op.f("ix_recommendations_player_key"))
        batch_op.drop_index(batch_op.f("ix_recommendations_outcome"))
        batch_op.drop_index(batch_op.f("ix_recommendations_market_type"))
        batch_op.drop_index(batch_op.f("ix_recommendations_input_hash"))
        batch_op.drop_index(batch_op.f("ix_recommendations_event_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_decision"))
        batch_op.drop_index(batch_op.f("ix_recommendations_created_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_chain_reaction_key"))
        batch_op.drop_index(batch_op.f("ix_recommendations_analysis_id"))
        batch_op.drop_index("ix_recommendations_analysis")

    op.drop_table("recommendations")
    with op.batch_alter_table("protocol_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_protocol_runs_user_id"))
        batch_op.drop_index(batch_op.f("ix_protocol_runs_status"))
        batch_op.drop_index(batch_op.f("ix_protocol_runs_sport"))
        batch_op.drop_index(batch_op.f("ix_protocol_runs_run_type"))
        batch_op.drop_index(batch_op.f("ix_protocol_runs_protocol_version"))
        batch_op.drop_index(batch_op.f("ix_protocol_runs_analysis_id"))

    op.drop_table("protocol_runs")
    with op.batch_alter_table("bankroll_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bankroll_accounts_user_id"))

    op.drop_table("bankroll_accounts")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("model_weights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_weights_sport"))
        batch_op.drop_index(batch_op.f("ix_model_weights_market_type"))
        batch_op.drop_index(batch_op.f("ix_model_weights_is_active"))
        batch_op.drop_index(batch_op.f("ix_model_weights_feature_name"))

    op.drop_table("model_weights")
    with op.batch_alter_table("game_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_snapshots_sport"))
        batch_op.drop_index(batch_op.f("ix_game_snapshots_slate_date"))
        batch_op.drop_index(batch_op.f("ix_game_snapshots_input_hash"))
        batch_op.drop_index(batch_op.f("ix_game_snapshots_event_id"))
        batch_op.drop_index(batch_op.f("ix_game_snapshots_analysis_id"))

    op.drop_table("game_snapshots")
    # ### end Alembic commands ###
