"""add live cashout audit

Revision ID: ae47f67d9aa5
Revises: 865f21ad51d1
Create Date: 2026-09-03 09:19:17.069599
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ae47f67d9aa5"
down_revision: str | Sequence[str] | None = "865f21ad51d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cashout_action", sa.String(length=24), nullable=True))
        batch_op.add_column(
            sa.Column("cashout_offer", sa.Numeric(precision=14, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("cashout_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("cashout_time", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_results_cashout_action"), ["cashout_action"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_results_cashout_action"))
        batch_op.drop_column("cashout_time")
        batch_op.drop_column("cashout_reason")
        batch_op.drop_column("cashout_offer")
        batch_op.drop_column("cashout_action")

    # ### end Alembic commands ###
